# PolicyDesk task runner. Run `just` to see all recipes.
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# Show the list of recipes
default:
    @just --list

# Install all dependencies (creates/updates uv.lock)
install:
    uv sync

# Lint, format-check and type-check (our code only: src + tests)
check:
    uv run ruff check src tests
    uv run ruff format --check src tests
    uv run mypy --strict src

# Run the tests
test:
    uv run pytest

# Run the app with autoreload (http://localhost:8000)
dev:
    uv run uvicorn policydesk.main:create_app --factory --reload

# Create a new autogenerated migration: just makemigrations msg="add table"
makemigrations msg:
    uv run alembic revision --autogenerate -m "{{msg}}"

# Apply all migrations
migrate:
    uv run alembic upgrade head

# Undo the last migration
downgrade:
    uv run alembic downgrade -1
