"""user_account.id: BIGSERIAL -> GENERATED BY DEFAULT AS IDENTITY

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-10

"""

from collections.abc import Sequence

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TABLE user_account ALTER COLUMN id DROP DEFAULT")
    op.execute("DROP SEQUENCE user_account_id_seq")
    op.execute("ALTER TABLE user_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    # Start after the biggest id, so old rows never clash with new ones.
    op.execute(
        "SELECT setval(pg_get_serial_sequence('user_account', 'id'), "
        "COALESCE(MAX(id), 0) + 1, false) FROM user_account"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE user_account ALTER COLUMN id DROP IDENTITY")
    op.execute("CREATE SEQUENCE user_account_id_seq OWNED BY user_account.id")
    op.execute(
        "ALTER TABLE user_account ALTER COLUMN id SET DEFAULT nextval('user_account_id_seq')"
    )
    op.execute(
        "SELECT setval('user_account_id_seq', COALESCE(MAX(id), 0) + 1, false) FROM user_account"
    )
