"""msg=add customer model

Revision ID: 33a46cd852f9
Revises: 0002
Create Date: 2026-10-11 13:27:11.328849

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '33a46cd852f9'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('id_type', sa.Enum('MYKAD', 'PASSPORT', name='idtype', native_enum=False, length=10), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('mobile', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id_type <> 'MYKAD' OR id_number ~ '^[0-9]{12}$'", name=op.f('ck_customer_mykad_12_digits')),
    sa.CheckConstraint("id_type IN ('MYKAD','PASSPORT')", name=op.f('ck_customer_id_type')),
    sa.CheckConstraint("mobile ~ '^\\+60[0-9]{8,10}$'", name=op.f('ck_customer_mobile_format')),
    sa.ForeignKeyConstraint(['agent_id'], ['user_account.id'], name=op.f('fk_customer_agent_id_user_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_customer_user_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('id_type', 'id_number', name=op.f('uq_customer_id_type_id_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_customer_user_id'))
    )
    op.create_index(op.f('ix_customer_agent_id'), 'customer', ['agent_id'], unique=False)
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_table('address',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('line1', sa.String(length=150), nullable=False),
    sa.Column('line2', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('postcode', sa.CHAR(length=5), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("postcode ~ '^[0-9]{5}$'", name=op.f('ck_address_postcode_format')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_address_customer_id_customer'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    op.create_index(op.f('ix_address_customer_id'), 'address', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_customer_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_agent_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
